### ISSUE TITLE
LOOP2-Kompatibilitätscheck für LOOP1

### ISSUE THREAD

**Issue by krohnden** [oncampus/mediawiki-extensions-Loop#46]
- Falsche Literatuverzeichniseinträge (siehe log1) mit doppelten Id-Einträgen sind verboten.
- loop_video und loop_audio tags entfernen

**Comment by duness** [comment]
Checken wie oft <spoiler>/<loop_spoiler> verwendet wird.

**Comment by krohnden** [comment]
Bedingung für Update: keine Seiten mit Änderungsvorschlägen! Sonst könnten auf Seiten, die Loop-Objekte beinhalten, ungeprüfte Änderungen automatisch übernommen werden.
