### ISSUE TITLE
Glossar

### ISSUE THREAD

**Issue by krohnden** [oncampus/mediawiki-extensions-Loop#56]
In LOOP1 als Kategorie umgesetzt. Eine Seite die ins Glossar soll wird über [[Kategorie:Glossar]] der Kategorie Glossar hinzugefügt.

In LOOP 2: Das Glossar wird in einem eigenen Mediawiki Namensraum umgesetzt, z.b. /loop/Glossar:Glossareintrag
Vorteil: Es kann in der Struktur eine Seite mit dem gleichen Namen geben.

 - [x] Namenraum anlegen
 - [ ] Überführung der alten Kategorieseiten in Namensraum
 - [x] Export

**Comment by oncampus** [comment]
In LOOP1 als Kategorie umgesetzt. Eine Seite die ins Glossar soll wird über [[Kategorie:Glossar]] der Kategorie Glossar hinzugefügt.

In LOOP 2: Das Glossar wird in einem eigenen Mediawiki Namensraum umgesetzt, z.b. /loop/Glossar:Glossareintrag
Vorteil: Es kann in der Sttruktur eine Seite mit dem gleichen Namen geben.

**Comment by krohnden** [comment]
BZGL Überführung:
Bei der ÜF alle Seiten nach Kategorie:Glossar (o.ä.) durchsuchen, Seite Glossar:Begriffsname anlegen und diese mit dem Inhalt der alten Seite (abzgl dem Kategorie-Teil) befüllen. Alte Seite leeren und Redirect auf die neue Glossar:Begriff Seite lenken.
So funktionieren alte Links noch.
-> was passiert, wenn man das neu auf alte Weise eingibt? Nichts?
